/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Prediction
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the LuisClient.
 */
export interface Prediction {


    /**
     * Gets the published endpoint predictions for the given query.
     *
     * @param {string} azureRegion Supported Azure regions for Cognitive Services
     * endpoints. Possible values include: 'westus', 'westeurope'
     *
     * @param {string} subscriptionKey Either Subscription Key or Programmatic Key.
     *
     * @param {string} q The query to predict.
     *
     * @param {string} appId Format - guid. The application ID.
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {number} [options.timezoneOffset] The timezone offset for the
     * location of the request.
     *
     * @param {boolean} [options.verbose] If true will return all intents instead
     * of just the topscoring intent.
     *
     * @param {boolean} [options.spellCheck] Enable spell checking.
     *
     * @param {boolean} [options.staging] Use staging endpoint.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<LuisResult>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getPredictionsFromEndpointViaGetWithHttpOperationResponse(azureRegion: string, subscriptionKey: string, q: string, appId: string, options?: { timezoneOffset? : number, verbose? : boolean, spellCheck? : boolean, staging? : boolean, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.LuisResult>>;

    /**
     * Gets the published endpoint predictions for the given query.
     *
     * @param {string} azureRegion Supported Azure regions for Cognitive Services
     * endpoints. Possible values include: 'westus', 'westeurope'
     *
     * @param {string} subscriptionKey Either Subscription Key or Programmatic Key.
     *
     * @param {string} q The query to predict.
     *
     * @param {string} appId Format - guid. The application ID.
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {number} [options.timezoneOffset] The timezone offset for the
     * location of the request.
     *
     * @param {boolean} [options.verbose] If true will return all intents instead
     * of just the topscoring intent.
     *
     * @param {boolean} [options.spellCheck] Enable spell checking.
     *
     * @param {boolean} [options.staging] Use staging endpoint.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {LuisResult} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {LuisResult} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link LuisResult} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getPredictionsFromEndpointViaGet(azureRegion: string, subscriptionKey: string, q: string, appId: string, options?: { timezoneOffset? : number, verbose? : boolean, spellCheck? : boolean, staging? : boolean, customHeaders? : { [headerName: string]: string; } }): Promise<models.LuisResult>;
    getPredictionsFromEndpointViaGet(azureRegion: string, subscriptionKey: string, q: string, appId: string, callback: ServiceCallback<models.LuisResult>): void;
    getPredictionsFromEndpointViaGet(azureRegion: string, subscriptionKey: string, q: string, appId: string, options: { timezoneOffset? : number, verbose? : boolean, spellCheck? : boolean, staging? : boolean, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.LuisResult>): void;


    /**
     * Gets the published endpoint prediction for the given long query.
     *
     * @param {string} azureRegion Supported Azure regions for Cognitive Services
     * endpoints. Possible values include: 'westus', 'westeurope'
     *
     * @param {string} appId Format - guid. The application ID.
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {number} [options.timezoneOffset] The timezone offset for the
     * location of the request.
     *
     * @param {boolean} [options.verbose] If true will return all intents instead
     * of just the topscoring intent.
     *
     * @param {boolean} [options.spellCheck] Enable spell checking.
     *
     * @param {boolean} [options.staging] Use staging endpoint.
     *
     * @param {string} [options.q] The query to predict.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<LuisResult>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getPredictionsFromEndpointViaPostWithHttpOperationResponse(azureRegion: string, appId: string, options?: { timezoneOffset? : number, verbose? : boolean, spellCheck? : boolean, staging? : boolean, q? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.LuisResult>>;

    /**
     * Gets the published endpoint prediction for the given long query.
     *
     * @param {string} azureRegion Supported Azure regions for Cognitive Services
     * endpoints. Possible values include: 'westus', 'westeurope'
     *
     * @param {string} appId Format - guid. The application ID.
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {number} [options.timezoneOffset] The timezone offset for the
     * location of the request.
     *
     * @param {boolean} [options.verbose] If true will return all intents instead
     * of just the topscoring intent.
     *
     * @param {boolean} [options.spellCheck] Enable spell checking.
     *
     * @param {boolean} [options.staging] Use staging endpoint.
     *
     * @param {string} [options.q] The query to predict.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {LuisResult} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {LuisResult} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link LuisResult} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getPredictionsFromEndpointViaPost(azureRegion: string, appId: string, options?: { timezoneOffset? : number, verbose? : boolean, spellCheck? : boolean, staging? : boolean, q? : string, customHeaders? : { [headerName: string]: string; } }): Promise<models.LuisResult>;
    getPredictionsFromEndpointViaPost(azureRegion: string, appId: string, callback: ServiceCallback<models.LuisResult>): void;
    getPredictionsFromEndpointViaPost(azureRegion: string, appId: string, options: { timezoneOffset? : number, verbose? : boolean, spellCheck? : boolean, staging? : boolean, q? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.LuisResult>): void;
}
