/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a EntityModel.
 */
class EntityModel {
  /**
   * Create a EntityModel.
   * @member {string} [entity]
   * @member {string} [type]
   * @member {number} [startIndex]
   * @member {number} [endIndex]
   */
  constructor() {
  }

  /**
   * Defines the metadata of EntityModel
   *
   * @returns {object} metadata of EntityModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EntityModel',
      type: {
        name: 'Composite',
        className: 'EntityModel',
        modelProperties: {
          entity: {
            required: false,
            serializedName: 'entity',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          startIndex: {
            required: false,
            serializedName: 'startIndex',
            type: {
              name: 'Number'
            }
          },
          endIndex: {
            required: false,
            serializedName: 'endIndex',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = EntityModel;
