/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Intent returned from LUIS.
 *
 */
class IntentModel {
  /**
   * Create a IntentModel.
   * @member {string} [intent]
   * @member {number} [score]
   */
  constructor() {
  }

  /**
   * Defines the metadata of IntentModel
   *
   * @returns {object} metadata of IntentModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'IntentModel',
      type: {
        name: 'Composite',
        className: 'IntentModel',
        modelProperties: {
          intent: {
            required: false,
            serializedName: 'intent',
            type: {
              name: 'String'
            }
          },
          score: {
            required: false,
            serializedName: 'score',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = IntentModel;
