/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a SimpleOrCompositeEntity.
 * @extends models['EntityModel']
 */
class SimpleOrCompositeEntity extends models['EntityModel'] {
  /**
   * Create a SimpleOrCompositeEntity.
   * @member {number} [score]
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of SimpleOrCompositeEntity
   *
   * @returns {object} metadata of SimpleOrCompositeEntity
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SimpleOrCompositeEntity',
      type: {
        name: 'Composite',
        className: 'SimpleOrCompositeEntity',
        modelProperties: {
          entity: {
            required: false,
            serializedName: 'entity',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          startIndex: {
            required: false,
            serializedName: 'startIndex',
            type: {
              name: 'Number'
            }
          },
          endIndex: {
            required: false,
            serializedName: 'endIndex',
            type: {
              name: 'Number'
            }
          },
          score: {
            required: false,
            serializedName: 'score',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = SimpleOrCompositeEntity;
