/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClient, ServiceClientOptions } from 'ms-rest';
import * as operations from "./operations";

declare class LuisClient extends ServiceClient {
  /**
   * @class
   * Initializes a new instance of the LuisClient class.
   * @constructor
   *
   * @param {object} [options] - The parameter options
   *
   * @param {Array} [options.filters] - Filters to be added to the request pipeline
   *
   * @param {object} [options.requestOptions] - Options for the underlying request object
   * {@link https://github.com/request/request#requestoptions-callback Options doc}
   *
   * @param {boolean} [options.noRetryPolicy] - If set to true, turn off default retry policy
   *
   */
  constructor(options?: ServiceClientOptions);

  // Operation groups
  prediction: operations.Prediction;
}

export = LuisClient;
