// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.CognitiveServices.LUIS.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EntityModel
    {
        /// <summary>
        /// Initializes a new instance of the EntityModel class.
        /// </summary>
        public EntityModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EntityModel class.
        /// </summary>
        public EntityModel(string entity = default(string), string type = default(string), double? startIndex = default(double?), double? endIndex = default(double?))
        {
            Entity = entity;
            Type = type;
            StartIndex = startIndex;
            EndIndex = endIndex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entity")]
        public string Entity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startIndex")]
        public double? StartIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endIndex")]
        public double? EndIndex { get; set; }

    }
}
