// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.CognitiveServices.LUIS.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SimpleOrCompositeEntity : EntityModel
    {
        /// <summary>
        /// Initializes a new instance of the SimpleOrCompositeEntity class.
        /// </summary>
        public SimpleOrCompositeEntity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SimpleOrCompositeEntity class.
        /// </summary>
        public SimpleOrCompositeEntity(string entity = default(string), string type = default(string), double? startIndex = default(double?), double? endIndex = default(double?), double? score = default(double?))
            : base(entity, type, startIndex, endIndex)
        {
            Score = score;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

    }
}
